<div class="container">
        <section class="article-zn container-fluid">

            <div class="button-div button-more-articles-zn">
                <button type="button" class="button" id="button-more-articles" onclick="location.href='index.html'">
                    Back home
                </button>
            </div>

            <div class="one-article-zn">
                <div class="one-article-layout col-12">
                    <div class="article-category-zn">
                        <div class="border-title-category category-one"></div>
                        <h4 class="category-text category-one-title">category one</h3>
                    </div>
                    <div class="article-txt-zn">
                        <h3 class="title-article">I will write some great</h3>
                        <p class="article-txt-info">Morgan Clark - Posted: 29/11/2019</p>
                        <p class="article-txt-main">Riat periore ptatis di ipicides utem dolorep eribus, occab illuptatque consequi deliquiberum quidunt, culloresciur ame quibusant quam aut opta experum cumet quis rae por rerspere aliberu ntotati ntiustiam, iuria cus aut deruptas doluptat...</p>
                        <p class="article-txt-main">Lorem ipsum dolor sit amet consectetur adipisicing elit. Alias harum at dolor sapiente nostrum, illo reiciendis nesciunt modi vel, exercitationem laboriosam dolore veritatis magnam maiores iste? Ullam esse modi eum cum quae, dignissimos ab repudiandae, adipisci quaerat voluptatem, praesentium dolor ex unde architecto aliquid enim! Perferendis amet ipsum in, architecto, necessitatibus accusantium, omnis facilis ipsa nisi minima voluptas porro ex officiis a quibusdam. Est nobis nulla repudiandae culpa. Facilis labore iusto, dolor nostrum saepe qui soluta tempora facere perferendis iste pariatur. Aperiam voluptas quibusdam pariatur dolore temporibus facilis quisquam accusamus, ratione repellendus at nobis tenetur fugit autem, sed debitis ab, ea commodi vitae architecto. Nostrum necessitatibus eum fugiat ad accusamus distinctio vel veritatis in ullam quam aperiam quod tenetur ipsa aspernatur quia odio laborum blanditiis pariatur omnis cum quas earum perferendis, magnam maiores. Earum quam dolore velit culpa, sed quas dolores cum repudiandae quibusdam doloribus! Sint voluptas omnis laboriosam harum enim, vero animi laborum ipsum, dolor nam et, repellendus tenetur labore libero provident velit eligendi consequuntur cupiditate reprehenderit vel? Tempora, odit ducimus sunt quod ipsa natus est eius dolorem iusto quisquam molestias sapiente ex tenetur obcaecati minus dolor dicta, fuga sequi eaque. Tempora ipsa quae similique, mollitia saepe rem. Ex.</p>
                        <p class="article-txt-main">Lorem ipsum dolor sit amet consectetur adipisicing elit. Alias harum at dolor sapiente nostrum, illo reiciendis nesciunt modi vel, exercitationem laboriosam dolore veritatis magnam maiores iste? Ullam esse modi eum cum quae, dignissimos ab repudiandae, adipisci quaerat voluptatem, praesentium dolor ex unde architecto aliquid enim! Perferendis amet ipsum in, architecto, necessitatibus accusantium, omnis facilis ipsa nisi minima voluptas porro ex officiis a quibusdam. Est nobis nulla repudiandae culpa. Facilis labore iusto, dolor nostrum saepe qui soluta tempora facere perferendis iste pariatur. Aperiam voluptas quibusdam pariatur dolore temporibus facilis quisquam accusamus, ratione repellendus at nobis tenetur fugit autem, sed debitis ab, ea commodi vitae architecto. Nostrum necessitatibus eum fugiat ad accusamus distinctio vel veritatis in ullam quam aperiam quod tenetur ipsa aspernatur quia odio laborum blanditiis pariatur omnis cum quas earum perferendis, magnam maiores. Earum quam dolore velit culpa, sed quas dolores cum repudiandae quibusdam doloribus! Sint voluptas omnis laboriosam harum enim, vero animi laborum ipsum, dolor nam et, repellendus tenetur labore libero provident velit eligendi consequuntur cupiditate reprehenderit vel? Tempora, odit ducimus sunt quod ipsa natus est eius dolorem iusto quisquam molestias sapiente ex tenetur obcaecati minus dolor dicta, fuga sequi eaque. Tempora ipsa quae similique, mollitia saepe rem. Ex.</p>
                        <p class="article-txt-main">Lorem ipsum dolor sit amet consectetur adipisicing elit. Alias harum at dolor sapiente nostrum, illo reiciendis nesciunt modi vel, exercitationem laboriosam dolore veritatis magnam maiores iste? Ullam esse modi eum cum quae, dignissimos ab repudiandae, adipisci quaerat voluptatem, praesentium dolor ex unde architecto aliquid enim! Perferendis amet ipsum in, architecto, necessitatibus accusantium, omnis facilis ipsa nisi minima voluptas porro ex officiis a quibusdam. Est nobis nulla repudiandae culpa. Facilis labore iusto, dolor nostrum saepe qui soluta tempora facere perferendis iste pariatur. Aperiam voluptas quibusdam pariatur dolore temporibus facilis quisquam accusamus, ratione repellendus at nobis tenetur fugit autem, sed debitis ab, ea commodi vitae architecto. Nostrum necessitatibus eum fugiat ad accusamus distinctio vel veritatis in ullam quam aperiam quod tenetur ipsa aspernatur quia odio laborum blanditiis pariatur omnis cum quas earum perferendis, magnam maiores. Earum quam dolore velit culpa, sed quas dolores cum repudiandae quibusdam doloribus! Sint voluptas omnis laboriosam harum enim, vero animi laborum ipsum, dolor nam et, repellendus tenetur labore libero provident velit eligendi consequuntur cupiditate reprehenderit vel? Tempora, odit ducimus sunt quod ipsa natus est eius dolorem iusto quisquam molestias sapiente ex tenetur obcaecati minus dolor dicta, fuga sequi eaque. Tempora ipsa quae similique, mollitia saepe rem. Ex.</p>
                    </div>
                </div>
            </div>
        </section>

    </div>